project:
  type: book
  output-dir: docs

book:
  title: "POSとマーケティングデータ分析"
  author:
    - name: "Soichi Matsuura"
    - affiliation: Ritsumeikan University
    - email: matsuura@fc.ritsumei.ac.jp
  date: "11/28/2024"
  favicon: img/favicon.ico
  twitter-card: true
  # site-url: https://so-ichi.com
  chapters:
    - index.qmd
    - POS_Marketing_01.qmd
    - POS_Marketing_02.qmd
    - POS_Marketing_03.qmd
    - POS_Marketing_04.qmd
    - POS_Marketing_05.qmd
    - POS_Marketing_06.qmd
    - POS_Marketing_07.qmd
  page-navigation: true
  back-to-top-navigation: true
  page-footer:
      border: true
      background: light
      left: "Copyright 2024, Soichi Matsuura"
      right:
        - icon: github
          href: https://github.com/ma2ura
        - icon: twitter
          href: https://twitter.com/matsuura_rits
          aria-label: Twitter

format:
  html:
    theme: cerulean
    toc: true
    html-math-method: katex
    code-copy: true
    code-overflow: wrap
    code-link: true
    link-external-icon: true
    df-print: kable
    grid:
      sidebar-width: 200px
      body-width: 1200px
    css:
      - "mystyle.css"
lang: "ja"
