project:
  type: book
  output-dir: docs

lightbox: auto

book:
  title: "POSとマーケティングデータ分析"
  author:
    - name: "Soichi Matsuura"
    - affiliation: Ritsumeikan University
    - email: matsuura@fc.ritsumei.ac.jp
  date: "11/28/2024"
  search: true
  # license: "CC BY-NC-SA"
  # cover-image: img/POS_data.jpg
  favicon: img/favicon.ico


  reader-mode: true
  google-analytics: "G-SFB56VHK63"
  page-navigation: true

  site-url: https://so-ichi.com
  repo-url: https://github.com/ma2ura/pos_marketing/
  repo-branch: main

  page-footer:
      border: true
      background: "#a10000"
      left: "Copyright 2026, Soichi Matsuura"
      right:
        - icon: github
          href: https://github.com/ma2ura
        - icon: twitter
          href: https://twitter.com/matsuura_rits
          aria-label: Twitter

  sidebar:
    style: docked
    background: light
    collapse: true

  chapters:
    - index.qmd
    - POS_Marketing_01.qmd
    - POS_Marketing_02.qmd
    - POS_Marketing_03.qmd
    - POS_Marketing_04.qmd
    - POS_Marketing_05.qmd
    - POS_Marketing_06.qmd
    - POS_Marketing_07.qmd

website:
  back-to-top-navigation: true

format:
  html:
    theme:
      light: united
      dark: cyborg
    mainfont: "Noto Sans JP"
    monofont: "0xProto" # ※このフォントがシステムにない場合、デフォルトになります

    toc: true
    toc-location: left
    toc-title: "ここの目次"
    toc-depth: 2
    toc-expand: true

    code-tools: true
    code-link: true
    code-line-numbers: true
    code-block-bg: true
    code-block-border-left: "#002D72"
    code-copy: hover
    code-overflow: scroll
    link-external-icon: true


    html-math-method: katex
    author-meta: "Soichi Matsuura"
    df-print: paged
    page-navigation: true
    back-to-top-navigation: true
    twitter-card: true

    include-in-header:
      text: |
        <style>
        .marky {
          background: linear-gradient(transparent 60%, #FCFFC1 0%);
        }
        .markb {
          background: linear-gradient(transparent 60%, #88E2EA 0%);
        }
        .markp{
          background: linear-gradient(transparent 70%, #ffcdd2 0%)
        }
        </style>

lang: "ja"
knitr:
  opts_chunk:
    dev: "ragg_png"
    dpi: 600

execute:
  error: false
  message: false
